//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMoec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farm
    {
        public farm()
        {
            this.plots = new HashSet<plot>();
        }
    
        public int farmId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string town { get; set; }
        public string county { get; set; }
        public string provinceCode { get; set; }
        public string postalCode { get; set; }
        public string homePhone { get; set; }
        public string cellPhone { get; set; }
        public string directions { get; set; }
        public Nullable<System.DateTime> dateJoined { get; set; }
        public Nullable<System.DateTime> lastContactDate { get; set; }
    
        public virtual province province { get; set; }
        public virtual ICollection<plot> plots { get; set; }
    }
}
