//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMoec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fertilizer
    {
        public fertilizer()
        {
            this.treatmentFertilizers = new HashSet<treatmentFertilizer>();
        }
    
        public string fertilizerName { get; set; }
        public bool OECProduct { get; set; }
        public bool liquid { get; set; }
    
        public virtual ICollection<treatmentFertilizer> treatmentFertilizers { get; set; }
    }
}
