//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMoec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plot
    {
        public plot()
        {
            this.treatments = new HashSet<treatment>();
        }
    
        public int plotId { get; set; }
        public Nullable<int> farmId { get; set; }
        public Nullable<int> varietyId { get; set; }
        public Nullable<System.DateTime> datePlanted { get; set; }
        public Nullable<System.DateTime> dateHarvested { get; set; }
        public Nullable<int> plantingRate { get; set; }
        public bool plantingRateByPounds { get; set; }
        public Nullable<int> rowWidth { get; set; }
        public Nullable<int> patternRepeats { get; set; }
        public Nullable<float> organicMatter { get; set; }
        public Nullable<float> bicarbP { get; set; }
        public Nullable<float> potassium { get; set; }
        public Nullable<float> magnesium { get; set; }
        public Nullable<float> calcium { get; set; }
        public Nullable<float> pHSoil { get; set; }
        public Nullable<float> pHBuffer { get; set; }
        public Nullable<float> CEC { get; set; }
        public Nullable<float> percentBaseSaturationK { get; set; }
        public Nullable<float> percentBaseSaturationMg { get; set; }
        public Nullable<float> percentBaseSaturationCa { get; set; }
        public Nullable<float> percentBaseSaturationH { get; set; }
        public string comments { get; set; }
    
        public virtual farm farm { get; set; }
        public virtual ICollection<treatment> treatments { get; set; }
        public virtual variety variety { get; set; }
    }
}
