//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMoec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatmentFertilizer
    {
        public int treatmentFertilizerId { get; set; }
        public Nullable<int> treatmentId { get; set; }
        public string fertilizerName { get; set; }
        public Nullable<float> ratePerAcre { get; set; }
        public string rateMetric { get; set; }
    
        public virtual fertilizer fertilizer { get; set; }
        public virtual treatment treatment { get; set; }
    }
}
