//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMoec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment
    {
        public treatment()
        {
            this.treatmentFertilizers = new HashSet<treatmentFertilizer>();
        }
    
        public int treatmentId { get; set; }
        public string name { get; set; }
        public int plotId { get; set; }
        public Nullable<float> moisture { get; set; }
        public Nullable<float> yield { get; set; }
        public Nullable<float> weight { get; set; }
    
        public virtual plot plot { get; set; }
        public virtual ICollection<treatmentFertilizer> treatmentFertilizers { get; set; }
    }
}
