//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMoec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class variety
    {
        public variety()
        {
            this.plots = new HashSet<plot>();
        }
    
        public int varietyId { get; set; }
        public Nullable<int> cropId { get; set; }
        public string name { get; set; }
    
        public virtual crop crop { get; set; }
        public virtual ICollection<plot> plots { get; set; }
    }
}
